### ISSUE TITLE
APP_ID not used - failing on App Not Found

### ISSUE THREAD

**Issue by sw564a** [cwtravis/bitbucket-asoc-sast-linux#3]
I'm getting this App Not Found error.

In the DEBUG it's referencing a different app.

Looking at the code, it is using "appId" that is set to a hard coded value that matches the app that is not found.

The value that I'm supplying through APP_ID is being set to a different variable (case sensitive appid) and it's also higher in the code path so even if it was appId, it would be overwritten with the hard coded value.

DEBUG: Checking AppId [9645f3f2-d116-48ec-8024-864948a86190]
DEBUG: Starting new HTTPS connection (1): [cloud.appscan.com:443](http://cloud.appscan.com:443/)
DEBUG: [https://cloud.appscan.com:443](https://cloud.appscan.com/) "GET /api/V2/Apps/9645f3f2-d116-48ec-8024-864948a86190 HTTP/1.1" 403 122
ERROR: Invalid AppId: App Not Found!
ERROR: Error creating scan

in linux/pipe/RunSAST.py
===================

        appid = self.get_variable('APP_ID')
...
        appId = "9645f3f2-d116-48ec-8024-864948a86190"
...
        scanId = self.runScan(scanName, appId, irxPath, comment, True)

**Comment by cwtravis** [comment]
Checking on the hard coded appid.

**Comment by cwtravis** [comment]
I removed the hard coded value and the scan should reflect the APP_ID in the environment variable set in the BitBucket pipeline yaml file.

**Comment by sw564a** [comment]
great.  i'll check it out.

**Comment by sw564a** [comment]
@cwtravis , thanks for the fix.  it works now.
